const translations = {
  es: {
     welcome: "EDUSOFT",
    subtitle: "Bienvenido a nuestra plataforma global de aprendizaje. Accede a material de estudio desde cualquier lugar y alcanza tus metas académicas. ¡Empieza hoy!",
    join_now: "Únete Ahora",

    iniciativas: "iniciativas",
    parrafo_i: "",
    leer_mas: "leer mas",

    mision: "mision",
    parrafo_m: "",

    noticias: "noticias",
    parrafo_n: "",

    participa: "participa",
    parrafo_p: "",

    abajo: "2025 en numeros",
    mil: "mil",
    dolares: "dolares recolectados",
    alumnos: "alumnos graduados",
    centros: "centros tecnologicos",

    inicio: "inicio",
    cursos: "cursos",
    nosotros: "nosotros",
    contacto: "contacto",
    biblioteca: "biblioteca",
    tutoriales: "tutoriales",
    preguntas_frecuentes: "preguntas frecuentes",
    soporte: "soporte",
    legal: "legal",
    terminos: "terminos",
    politica: "politica",
    cookies: "",

    copy: "2024 EDUSOFT - Plataforma Educativa. Desarrollado por estudiantes de Bachillerato Técnico.",

    innovacion: "Innovacion Educativa digital",
    estudiantes: "Estudiantes",
    prefesores: "Profesores",
    materias: "Materias",
    bienvenida: "Bienvenido de nuevo a nuestra plataforma educativa",
    bienvenida2: "Bienvenido  a nuestra plataforma educativa",
    desarrollo: "desarrollada por estudiantes,para estudiantes y profesores",
    educador: "Educador",
    soyprofe: "Soy profesor",
    p_profe: "Herramientras avanzadas para crear,gestionar y evaluar contenido educativo de manera eficiencite ",
    gestion: "Gestion de clases",
    subir: "Subir contenido",
    analasis: "Analasis de progeso",
    evaluaciones: "Evaluaciones",
    acceder_como: "Acceder como profesor ",
    estudiante: "Estudiante",
    soyestudiante: "Soy estudiante",
    p_estudiante: "accede a cursos interactivos,realiza actividades y sigue tu proceso academico y personalizado",
    cursos: "Cursos interactivos",
    actividades: "Actividades",
    logros: "Logros",
    progreso: "Mi progeso",
    acceder_estudiante: "Acceder como estudiante",
    porque: "¿Porque elegir nuestra plataforma?",
    desorrollada: "Desarrollado por estudiantes",
    creado:"Creado por estudiantes de bachillerato tecnico que entienden las necesidades reales del aprendizaje modern",
    tecnologias: "Tecnologia moderna",
    tecnologia: "Utilizamos las ultimas tecnologias web para ofrecer una experencia rapida,segiura,y confiable",
    comunidad: "Comunidad activa",
    aprendizaje: "Unete a una comunidad de aprendizaje donde estudiantes y profesores colaboran activamente ",
    edusoft: "Desarrollado con por estudiantes de bachillerato tecnico",
    nosotros: "Nosotros",
    ayuda: "Ayuda ",
    contacto: "Contacto",
    bienvenidaD:"Bienvenido Docente",
    cuentaD:"Crear una cuentra",
    nombre_usuario:"Nombre de usuario",
    correo:"Correo electronico",
    contraseña:"Contraseña",
    telefono:"Telefono",
    Dui:"Dui",
    registrar:"registrarse",
    denuevo:"Bienvenido de nuevo estudiante",
    inicioS:"Inicio de sesion",
    correcto:"Te registrate correctamente",
    iniciar:"start",
    denuevoD:"Bienvendia de nuevo Docente",
    confirmar:"confirmar contraseña",
    inicioN:"Inicio",
    ProgramasN:"Programas academicos",
    ActividadesN:"Acrtividades extrarriculares",
    primaria:"Primaria",
    secundaria:"Secundaria",
    bachillerato:"Bachillerato",
    cursosN:"Cursos",
    biologiaN:"Biologia",
    lenguajeN:"Lenguaje",
    cienciasN:"Ciencias",
    matematicasN:"Matematicas",
    quimicaN:"Quimica",
    Ciencias_socialesN:"Ciencias sociales",
    calendario:"Calendario",
    nosotros:"Nosotros",
    comunidadN:"Comunidad",
    profesoresN:"Profesores",
    alumnos:"Alumnos",
    padresN:"Padres",
    exalumnos:"Ex-alumnos",
    noticiasN:"Noticias",
    contactoN:"Contacto",
    cerrarN:"Cerrar sesion",
    bienvenido:"Bienvenido",
    cursos:"Nuestros cursos",
    biologia:"Biologia",
    lenguaje:"Lenguaje",
    ciencias:"Ciencias",
    matematicas:"Matematicas",
    mas_informacion:"mas informacion",
    noso:"nosotros",
    Nestudiantes:"Estudiantes de bachillerato técnico creando el futuro de la educación digital",
    somosN:"Quienes somos",
    somosP:"Somos un equipo de estudiantes apasionados del Bachillerato Técnico en Desarrollo de Software del Colegio Don Bosco. Nuestra plataforma educativa nació como un proyecto escolar que evolucionó hasta convertirse en una herramienta integral para el aprendizaje digital.",
    somosP2:"Combinamos nuestros conocimientos técnicos con una visión fresca de la educación para crear soluciones innovadoras que faciliten el acceso al conocimiento. Creemos que la tecnología debe ser un puente, no una barrera, para el aprendizaje efectivo.",
    somosp3:"Democratizar el acceso a la educación de calidad mediante herramientas tecnológicas innovadoras, desarrolladas por y para estudiantes, que faciliten el aprendizaje colaborativo y personalizado.",
    somosp4:"Ser reconocidos como pioneros en el desarrollo de soluciones educativas digitales creadas por estudiantes, inspirando a nuevas generaciones a utilizar la tecnología como herramienta de transformación social.",
    somosp5:"Buscamos constantemente nuevas formas de mejorar la experiencia educativa a través de la tecnología.",
    somosp6:"Creemos en el poder del trabajo en equipo y el intercambio de conocimientos para lograr objetivos comunes.",
    somosp7:"Nos esforzamos por hacer que el conocimiento sea accesible para todos, independientemente de sus circunstancias.",
    somosp8:"Nos comprometemos a ofrecer la más alta calidad en cada aspecto de nuestra plataforma educativa.",
    somosp9:"Somos estudiantes del Bachillerato Técnico en Desarrollo de Software, unidos por la pasión de crear soluciones tecnológicas para la educación. Cada uno aporta habilidades únicas que, en conjunto, nos permiten desarrollar una plataforma educativa completa y funcional.",
    somosp10:"Comenzamos como un proyecto escolar para la feria de ciencias del colegio, con la idea de crear una simple plataforma de recursos educativos.",
    somosp11:"Desarrollamos la primera versión funcional de la plataforma y comenzamos a implementarla en algunas clases de nuestro colegio.",
    somosp12:"Expandimos la plataforma para incluir más materias y funcionalidades, recibiendo reconocimiento a nivel regional por nuestra iniciativa.",
    somosp13:"Hoy nuestra plataforma es utilizada por estudiantes de diferentes instituciones, y seguimos trabajando para mejorarla cada día.",
    misionN:"Nuestra mision",
    visionN:"Nuestra vision",
    valoresN:"Nuestros Valores",
    innovacionN:"Innovacion",
    colaboracion:"Colaboracion",
    accesibilidad:"Accesibilidad",
    excelencia:"Excelencia",
    nuestroN:"Nuestro Equipo",
    front:"Desarrollo Frontend",
    especialista:"Especialista en crear interfaces intuitivas y atractivas para nuestra plataforma.",
    back:"Desarrollo backend",
    experto:"Experto en la lógica y funcionamiento interno de nuestra plataforma educativa.",
    trayectoria:"Nuestra Trayectoria",
    elN:"El Inicio",
    pasos:"Primeros Pasos",
    crecimiento:"Crecimiento",
    actualidad:"Actualidad",
    tablon:"Tablon",
    tareas:"Tareas",
    alumnos:"Alumnos",
    avisos:"Avisos",
    segundo:"Segundo año B",
    biologiaM:"Biologia",
    profesor:"profesor",
    titulo:"titulo",
    descripcion:"descripcion",
    fechal:"fecha de entrega",
    archivo:"Ver archivo adjunto",
    notareas:"No se han asignado tareas aun ",
    tareas:"tareas",
    tarea:"Tarea de Biología Celular",
    resolver:"Resolver los problemas de biología celular del capítulo 3.",
    fecha:"Fecha límite: 10 de abril",
    sube:"Sube tu tarea de Biología",
    archivo2:"Archivo (PDF, DOCX, JPG...):",
    subir:"Subir tarea",
    subidas:"Tareas subidas",
    proyecto:"Proyecto de Biología Molecular",
    crearM:"Crear un proyecto sobre la biología molecular.",
    limete:"Fecha límite: 12 de abril",
    añadir:"Añadir tarea",
    examen:"Examen de Biología Evolutiva",
    estudiar:"Estudiar para el examen de biología evolutiva que se realizará el próximo viernes.",
    tarea2:"Tarea de Biología Ambiental",
    escribir:"Escribir un ensayo sobre la importancia de la biología ambiental en la conservación del medio ambiente.",
    lista:"Lista de Alumnos",
    avisos:"Avisos",
    titulo2:"Título de la tarea",
    descripcionB:"Descripción de la tarea",
    archivos:"Subir archivos:",
    enlace:"Añadir enlace:",
    agregarE:"Agregar enlace",
    ciencia:"cienia",
    tareaC:"Tarea de Física",
    cp1:"Resolver los problemas de física del capítulo 3.",
    astronomia:"Proyecto de Astronomía<",
    cp2:"Crear un proyecto sobre el sistema solar.",
    geologia:"Examen de Geología",
    cp3:"Estudiar para el examen de geología que se realizará el próximo viernes.",
    ambiental:"Tarea de Ciencia Ambiental",
    cp4:"Escribir un ensayo sobre la importancia de la conservación del medio ambiente.",
    lenguajeM:"Lenguaje y literatura",
    analasisM:"Tarea de Análisis de Texto",
    lp:"Analizar el texto La casa de los espíritus de Isabel Allende",
    proyectol:"Proyecto de Literatura",
    lp1:"Crear un proyecto sobre la vida y obra de un autor literario.",
    examenl:"Examen de Gramática",
    lp2:"Estudiar para el examen de gramática que se realizará el próximo viernes.",
    composicionl:"Tarea de Composición",
    lp3:"Escribir un ensayo sobre un tema de actualidad.",
    h4:"plataforma",
    recursosP:"recursos",
    acceder_estudiante1:"Continuar como estudiante",
    acceder_como1:"Continuar como profesor",
    inicioV:"Inicio",
    nosotrosV:"Nosotros",
    contactoV:"contacto",
    inicairS:"iniciar sesion",
    unete:"Unete",
    nombreCo:" Nombre y apellido",
    correoCo:"Correo electronico",
    asuntoCo:"Asunto",
    escribe:"Escribe tu mensaje ",
    enviarCo:"Enviar mensaje",




    

    

  



  


  

             
             


    // Agrega más claves y textos en español
  },
  en: {
    welcome: "EDUSOFT",
    subtitle: "Welcome to our global learning platform. Access study material from anywhere and achieve your academic goals. Start today!",
    join_now: "Join Now",
    iniciativas:"Initiatives" ,
    parrafo_i: "",
    leer_mas:"read more" ,
    mision:"Mission" ,
    parrafo_m: "Help all students who lack the technology or services to integrate into a better, more advanced education.",
    leer_mas: "read more",
    noticias:"News",
    parrafo_n:"",
    leer_mas:"read more",
    participa:"Participate",
    parrafo_p: "",
    leer_mas:"read more",
    abajo: "2025 in numbers",
    mil:"thousand",
    dolares:"Dollars collected",
    alumnos:"Students graduates",
    centros:"Centers technological",
    inicio:"start",
    cursos:"courses",
    nosotros:"us",
    contacto:"contact",
    biblioteca:"library",
    tutoriales:"tutorials",
    preguntas_frecuentes:"frequently asked questions",
    soporte:"medium",
    legal:"legal",
    terminos:"Terms of Use",
    politica:"Privacy Policy",
    cookies:"Cookies",
    copy:"2024 EDUSOFT - Educational Platform. Developed by technical high school students.", 
    innovacion:"Digital Educational Innovation",
    estudiantes:"students",
    prefesores:"teachers",
    materias:"subjects",
    bienvenida:"Welcome back to our educational platform.",
    bienvenida2: "Welcome to our educational platform",
    desarrollo:"Developed by students, for students and teachers",
    educador:"Educator",
    soyprofe:"I am a teacher",
    p_profe:"Advanced tools to efficiently create, manage, and evaluate educational content",
    gestion:"Class Management",
    subir:"Upload Content",
    analasis:"Progress Analysis",
    evaluaciones:"Evaluations",
    acceder_como:"Access as a teacher",
    estudiante:"Student",
    soyestudiante:"I am student",
    p_estudiante:"Access interactive courses, complete activities, and track your personalized academic progress.",
    cursos:"Interactive Courses",
    actividades:"Actividades",
    logros:"Achievements",
    progreso:"My Progress",
    acceder_estudiante:"Access as a Student",
    porque:"Why choose our platform?",
    desorrollada:"Developed by Students",
    creado:"Created by technical high school students who understand the real needs of modern learning",
    tecnologias:"Modern Technology",
    tecnologia:"We use the latest web technologies to offer a fast, secure and reliable experience",
    comunidad:"Active Community",
    aprendizaje:"Únete a una comunidad de aprendizaje donde estudiantes y profesores colaboran activamente",
    edusoft:"Developed with by Technical Baccalaureate students",
    nosotros:"our",
    ayuda:"help",
    contacto:"contact",
    bienvenidaD:"Welcome teacher",
    cuentaD:"Create an Account",
    nombre_usuario:"User name",
    correo:"Email",
    contraseña:"password",
    telefono:"phone",
    Dui:"ID",
    campos:"All fields are required",
    correcion:"You have registered successfully",
    bienvenidaE:"Welcome student",
    registrar:"Register",
    denuevo:"Welcome back student",
    inicioS:"Login",
    correcto:"Register correctly",
    iniciar:"start",
    denuevoD:"Welcome back teacher",
    confirmar:"confirm password",
    inicioN:"start",
    ProgramasN:"Academic Programs",
    ActividadesN:"Extracurricular activities",
    primaria:"Primary",
    secundaria:"Secondary",
    bachillerato:"High school",
    cursosN:"Courses",
    biologiaN:"Biology",
    lenguajeN:"Language",
    cienciasN:"Science",
    matematicasN:"Matemática",
    quimicaN:"Chemistry",
    Ciencias_socialesN:"Social Sciences",
    calendario:"Calendar",
    nosotros:"Us",
    comunidadN:"Comunidad",
    profesoresN:"Teachers",
    alumnos:"Students",
    padresN:"Parents",
    exalumnos:"alumni",
    noticiasN:"News",
    contactoN:"Contact ",
    cerrarN:"fail session",
    bienvenido:"Welcome",
    cursos:"Our courses",
    biologia:"Biology",
    lenguaje:"Lenguage",
    ciencias:"Science",
    matematicas:"mathematicas",
    mas_informacion:"more information",
    noso:"US",
    Nestudiantes:"Technical high school students creating the future of digital education",
    somosN:"Who We Are",
    somosP2:"We combine our technical expertise with a fresh vision of education to create innovative solutions that facilitate access to knowledge. We believe that technology should be a bridge, not a barrier, to effective learning.",
    somosP:"We are a team of passionate students from the Technical Baccalaureate in Software Development at Don Bosco School. Our educational platform began as a school project and has evolved into a comprehensive tool for digital learning.",
    somosp3:"Democratize access to quality education through innovative technological tools, developed by and for students, that facilitate collaborative and personalized learning.",
    somosp4:"To be recognized as pioneers in the development of student-created digital educational solutions, inspiring new generations to use technology as a tool for social transformation.",
    somosp5:"We are constantly looking for new ways to enhance the educational experience through technology.",
    somosp6:"We believe in the power of teamwork and knowledge sharing to achieve common goals.",
    somosp7:"We strive to make knowledge accessible to everyone, regardless of their circumstances.",
    somosp8:"We are committed to providing the highest quality in every aspect of our educational platform.",
    somosp9:"We are students of the Technical Baccalaureate in Software Development, united by a passion for creating technological solutions for education. Each of us brings unique skills that, together, allow us to develop a complete and functional educational platform.",
    somosp10:"We started as a school project for the school science fair, with the idea of creating a simple educational resource platform.",
    somosp11:"We developed the first functional version of the platform and began implementing it in some classes at our school.",
    somosp12:"We expanded the platform to include more subjects and features, receiving regional recognition for our initiative.",
    somosp13:"Today, our platform is used by students from different institutions, and we continue working to improve it every day.",
    misionN:"Our Mission",
    visionN:"Our Vision",
    valoresN:"Our Values",
    innovacionN:"Innovation",
    colaboracion:"Collaboration",
    accesibilidad:"Accessibility",
    excelencia:"Excellence",
    nuestroN:"Our Team",
    front:"Frontend Development",
    especialista:"Specialist in creating intuitive and attractive interfaces for our platform.",
    back:"Backend Development",
    experto:"Expert in the logic and inner workings of our educational platform.",
    trayectoria:"Our Trajectory",
    elN:"The Start",
    pasos:"First Steps",
    crecimiento:"growth",
    actulidad:"Present",
    profesor:"teacher",
    subidas:"uploaded tasks",
    tablon:"Plank",
    tareas:"Homeworks",
    alumnos:"Students",
    avisos:"notices",
    segundo:"Second year B",
    biologiaM:"Biology",
    titulo:"title",
    descripcion:"description",
    fechal:"Deadline",
    archivo:"See attached file",
    notareas:"No tasks have been assigned yet.",
    tarea:"Cell Biology Homework",
    resolver:"Solve the cell biology problems from chapter 3.",
    fecha:"Deadline: April 10",
    sube:"Upload your Biology homework",
    archivo2:"File (PDF, DOCX, JPG...):",
    subir:"UpUploaded tasks",
    proyecto:"Create a Molecular Biology Project",
    crearM:"Create a project on molecular biology.",
    limete:"Deadline: April 12",
    añadir:"Add task",
    examen:"Evolutionary Biology Exam",
    estudiar:"Study for the evolutionary biology exam next Friday.",
    tarea2:"Environmental Biology Homework",
    escribir:"Write an essay on the importance of environmental biology in environmental conservation.",
    lista:"List of Students",
    avisos:"Notices",
    titulo2:"Task Title",
    descripcionB:"Task description",
    archivos:"Upload files",
    enlace:"Add link:",
    agregarE:"Add link",
    ciencia:"science",
    tareaC:"Physics Homework",
    cp1:"Astronomy Project",
    astronomia:"Astronomy Project",
    cp2:"Create a project about the solar system.",
    geologia:"Geology Exam",
    cp3:"Study for the geology exam next Friday.",
    ambiental:"Environmental Science Homework",
    cp4:"Write an essay on the importance of environmental conservation.",
    lenguajeM:"lenguage",
    analasisM:"Text Analysis Task",
    lp:"Analyze the text The House of the Spirits by Isabel Allende",
    proyectol:"Literature Project",
    lp1:"Create a project about the life and work of a literary author.",
    examenl:"Grammar Test",
    lp2:"Study for the grammar test next Friday.",
    composicionl:"Composition Task",
    lp3:"Write an essay on a current topic.",
    h4:"platform",
    recursosP:"resources",
    acceder_estudiante1:"Login as a student",
    acceder_como1:"Login as a teacher",
    inicioV:"Main",
    nosotrosV:"US",
    contactoV:"contact",
    iniciarS:"Login",
    unete:"join",
    nombreCo:"Full name",
    correoCo:"Email",
    asuntoCo:"Affair",
    escribe:"Write your message...",
    enviarCo:"Send message",


    

    

  
  
  
  
  }
};