const translations = {
  es: {
     welcome: "EDUSOFT",
    subtitle: "Bienvenido a nuestra plataforma global de aprendizaje. Accede a material de estudio desde cualquier lugar y alcanza tus metas académicas. ¡Empieza hoy!",
    join_now: "Únete Ahora",

    iniciativas: "iniciativas",
    parrafo_i: "",
    leer_mas: "leer mas",

    mision: "mision",
    parrafo_m: "",

    noticias: "noticias",
    parrafo_n: "",

    participa: "participa",
    parrafo_p: "",

    abajo: "2025 en numeros",
    mil: "mil",
    dolares: "dolares recolectados",
    alumnos: "alumnos graduados",
    centros: "centros tecnologicos",

    inicio: "Inicio",
    cursos: "Cursos",
    nosotros: "Nosotros",
    contacto: "Contacto",
    biblioteca: "Biblioteca",
    tutoriales: "Tutoriales",
    preguntas_frecuentes: "Preguntas frecuentes",
    soporte: "Soporte",
    legal: "Legal",
    terminos: "Terminos",
    politica: "Politica",
    cookies: "",

    copy: "2024 EDUSOFT - Plataforma Educativa. Desarrollado por estudiantes de Bachillerato Técnico.",

    innovacion: "Innovacion Educativa digital",
    estudiantes: "Estudiantes",
    prefesores: "Profesores",
    materias: "Materias",
    bienvenida: "Bienvenido de nuevo a nuestra plataforma educativa",
    bienvenida2: "Bienvenido  a nuestra plataforma educativa",
    desarrollo: "Desarrollada por estudiantes,para estudiantes y profesores",
    educador: "Educador",
    soyprofe: "Soy profesor",
    p_profe: "Herramientras avanzadas para crear,gestionar y evaluar contenido educativo de manera eficiencite ",
    gestion: "Gestion de clases",
    subir: "Subir contenido",
    analasis: "Analasis de progeso",
    evaluaciones: "Evaluaciones",
    acceder_como: "Acceder como profesor ",
    estudiante: "Estudiante",
    soyestudiante: "Soy estudiante",
    p_estudiante: "Accede a cursos interactivos,realiza actividades y sigue tu proceso academico y personalizado",
    cursos: "Cursos interactivos",
    actividades: "Actividades",
    logros: "Logros",
    progreso: "Mi progeso",
    acceder_estudiante: "Acceder como estudiante",
    porque: "¿Por qué elegir nuestra plataforma?",
    desorrollada: "Desarrollado por estudiantes",
    creado:"Creado por estudiantes de bachillerato tecnico que entienden las necesidades reales del aprendizaje modern",
    tecnologias: "Tecnologia moderna",
    tecnologia: "Utilizamos las ultimas tecnologias web para ofrecer una experencia rapida, segura y confiable",
    comunidad: "Comunidad activa",
    aprendizaje: "Unete a una comunidad de aprendizaje donde estudiantes y profesores colaboran activamente ",
    edusoft: "Desarrollado con por estudiantes de bachillerato tecnico",
    nosotros: "Nosotros",
    ayuda: "Ayuda ",
    contacto: "Contacto",
    bienvenidaD:"Bienvenido Docente",
    cuentaD:"Crear una cuenta",
    nombre_usuario:"Nombre de usuario",
    correo:"Correo electrónico",
    contraseña:"Contraseña",
    telefono:"Teléfono",
    Dui:"DUI",
    registrar:"Registrarse",
    denuevo:"Bienvenido de nuevo estudiante",
    inicioS:"Inicio de sesión",
    correcto:"Te registraste correctamente",
    iniciar:"Iniciar Sesión",
    denuevoD:"Bienvendia de nuevo Docente",
    confirmar:"Confirmar contraseña",
    inicioN:"Inicio",
    ProgramasN:"Programas académicos",
    ActividadesN:"Actividades extrarriculares",
    primaria:"Primaria",
    secundaria:"Secundaria",
    bachillerato:"Bachillerato",
    cursosN:"Cursos",
    biologiaN:"Biologia",
    lenguajeN:"Lenguaje",
    cienciasN:"Ciencias",
    matematicasN:"Matematicas",
    quimicaN:"Quimica",
    Ciencias_socialesN:"Ciencias sociales",
    calendario:"Calendario",
    nosotros:"Nosotros",
    comunidadN:"Comunidad",
    profesoresN:"Profesores",
    alumnos:"Alumnos",
    padresN:"Padres",
    exalumnos:"Ex-alumnos",
    noticiasN:"Noticias",
    contactoN:"Contacto",
    cerrarN:"Cerrar sesión",
    bienvenido:"Bienvenido",
    cursos:"Nuestros cursos",
    biologia:"Biología",
    lenguaje:"Lenguaje",
    ciencias:"Ciencias",
    matematicas:"Matematicas",
    mas_informacion:"Más informacion",
    noso:"Nosotros",
    Nestudiantes:"Estudiantes de bachillerato técnico creando el futuro de la educación digital",
    somosN:"Quiénes somos",
    somosP:"Somos un equipo de estudiantes apasionados del Bachillerato Técnico en Desarrollo de Software del Colegio Don Bosco. Nuestra plataforma educativa nació como un proyecto escolar que evolucionó hasta convertirse en una herramienta integral para el aprendizaje digital.",
    somosP2:"Combinamos nuestros conocimientos técnicos con una visión fresca de la educación para crear soluciones innovadoras que faciliten el acceso al conocimiento. Creemos que la tecnología debe ser un puente, no una barrera, para el aprendizaje efectivo.",
    somosp3:"Democratizar el acceso a la educación de calidad mediante herramientas tecnológicas innovadoras, desarrolladas por y para estudiantes, que faciliten el aprendizaje colaborativo y personalizado.",
    somosp4:"Ser reconocidos como pioneros en el desarrollo de soluciones educativas digitales creadas por estudiantes, inspirando a nuevas generaciones a utilizar la tecnología como herramienta de transformación social.",
    somosp5:"Buscamos constantemente nuevas formas de mejorar la experiencia educativa a través de la tecnología.",
    somosp6:"Creemos en el poder del trabajo en equipo y el intercambio de conocimientos para lograr objetivos comunes.",
    somosp7:"Nos esforzamos por hacer que el conocimiento sea accesible para todos, independientemente de sus circunstancias.",
    somosp8:"Nos comprometemos a ofrecer la más alta calidad en cada aspecto de nuestra plataforma educativa.",
    somosp9:"Somos estudiantes del Bachillerato Técnico en Desarrollo de Software, unidos por la pasión de crear soluciones tecnológicas para la educación. Cada uno aporta habilidades únicas que, en conjunto, nos permiten desarrollar una plataforma educativa completa y funcional.",
    somosp10:"Comenzamos como un proyecto escolar para la feria de ciencias del colegio, con la idea de crear una simple plataforma de recursos educativos.",
    somosp11:"Desarrollamos la primera versión funcional de la plataforma y comenzamos a implementarla en algunas clases de nuestro colegio.",
    somosp12:"Expandimos la plataforma para incluir más materias y funcionalidades, recibiendo reconocimiento a nivel regional por nuestra iniciativa.",
    somosp13:"Hoy nuestra plataforma es utilizada por estudiantes de diferentes instituciones, y seguimos trabajando para mejorarla cada día.",
    misionN:"Nuestra misión",
    visionN:"Nuestra visión",
    valoresN:"Nuestros Valores",
    innovacionN:"Innovación",
    colaboracion:"Colaboración",
    accesibilidad:"Accesibilidad",
    excelencia:"Excelencia",
    nuestroN:"Nuestro Equipo",
    front:"Desarrollo Frontend",
    especialista:"Especialista en crear interfaces intuitivas y atractivas para nuestra plataforma.",
    back:"Desarrollo Backend",
    experto:"Experto en la lógica y funcionamiento interno de nuestra plataforma educativa.",
    trayectoria:"Nuestra Trayectoria",
    elN:"El Inicio",
    pasos:"Primeros Pasos",
    crecimiento:"Crecimiento",
    actualidad:"Actualidad",
    tablon:"Tablon",
    tareas:"Tareas",
    alumnos:"Alumnos",
    avisos:"Avisos",
    segundo:"Segundo año B",
    biologiaM:"Biologia",
    profesor:"profesor",
    titulo:"Titulo",
    descripcion:"Descripcion",
    fechal:"Fecha de entrega",
    archivo:"Ver archivo adjunto",
    notareas:"No se han asignado tareas aun ",
    tareas:"Tareas",
    tarea:"Tarea de Biología Celular",
    resolver:"Resolver los problemas de biología celular del capítulo 3.",
    fecha:"Fecha límite: 10 de abril",
    sube:"Sube tu tarea de Biología",
    archivo2:"Archivo (PDF, DOCX, JPG...):",
    subir:"Subir tarea",
    subidas:"Tareas subidas",
    proyecto:"Proyecto de Biología Molecular",
    crearM:"Crear un proyecto sobre la biología molecular.",
    limete:"Fecha límite: 12 de abril",
    añadir:"Añadir tarea",
    examen:"Examen de Biología Evolutiva",
    estudiar:"Estudiar para el examen de biología evolutiva que se realizará el próximo viernes.",
    tarea2:"Tarea de Biología Ambiental",
    escribir:"Escribir un ensayo sobre la importancia de la biología ambiental en la conservación del medio ambiente.",
    lista:"Lista de Alumnos",
    avisos:"Avisos",
    titulo2:"Título de la tarea",
    descripcionB:"Descripción de la tarea",
    archivos:"Subir archivos:",
    enlace:"Añadir enlace:",
    agregarE:"Agregar enlace",
    ciencia:"Ciencia",
    tareaC:"Tarea de Física",
    cp1:"Resolver los problemas de física del capítulo 3.",
    astronomia:"Proyecto de Astronomía<",
    cp2:"Crear un proyecto sobre el sistema solar.",
    geologia:"Examen de Geología",
    cp3:"Estudiar para el examen de geología que se realizará el próximo viernes.",
    ambiental:"Tarea de Ciencia Ambiental",
    cp4:"Escribir un ensayo sobre la importancia de la conservación del medio ambiente.",
    lenguajeM:"Lenguaje y literatura",
    analasisM:"Tarea de Análisis de Texto",
    lp:"Analizar el texto La casa de los espíritus de Isabel Allende",
    proyectol:"Proyecto de Literatura",
    lp1:"Crear un proyecto sobre la vida y obra de un autor literario.",
    examenl:"Examen de Gramática",
    lp2:"Estudiar para el examen de gramática que se realizará el próximo viernes.",
    composicionl:"Tarea de Composición",
    lp3:"Escribir un ensayo sobre un tema de actualidad.",
    h4:"Plataforma",
    recursosP:"Recursos",
    acceder_estudiante1:"Continuar como estudiante",
    acceder_como1:"Continuar como profesor",
    inicioV:"Inicio",
    nosotrosV:"Nosotros",
    contactoV:"Contacto",
    inicairS:"iniciar sesion",
    unete:"Unete",
    nombreCo:" Nombre y apellido",
    correoCo:"Correo electrónico",
    asuntoCo:"Asunto",
    escribe:"Escribe tu mensaje ",
    enviarCo:"Enviar mensaje",
    ActividadesE: "Materias escolares",
    cursosE: "Materias extracurriculares",
    titulo_arte: "EduSoft - Arte",
    logo_edusoft: "EduSoft",
    tablon: "Tablón",
    tareas: "Tareas",
    alumnos: "Alumnos",
    arte_titulo_principal: "Arte",
    arte_descripcion: "Explora el mundo del arte y desarrolla tu creatividad a través de diferentes actividades y proyectos.",
    arte_titulo_tareas: "Tareas de Arte",
    arte_tarea_1: "Realiza un dibujo libre y súbelo antes del viernes.",
    arte_tarea_2: "Investiga sobre un pintor famoso y comparte tu trabajo.",
    arte_titulo_alumnos: "Lista de Alumnos",
    arte_alumno_1: "Juan Pérez",
    arte_alumno_2: "María López",
    arte_alumno_3: "Carlos Gómez",
    titulo_deportes: "EduSoft - Deportes",
    logo_edusoft: "EduSoft",
    tablon: "Tablón",
    tablon_texto: "Tablón",
    tareas: "Tareas",
    tareas_texto: "Tareas",
    material_texto: "Material",
    alumnos: "Alumnos",
    alumnos_texto: "Alumnos",
    avisos: "Avisos",
    avisos_texto: "Avisos",
    segundo: "Segundo año B",
    segundo_texto: "Segundo año B",
    deportesN: "Deportes",
    settings: "Configuración",
    profile: "Perfil",
    profesor: "Profesor",
    titulo: "Título",
    descripcion: "Descripción",
    fechal: "Fecha límite",
    puntos: "Puntos",
    archivo: "Archivo adjunto",
    archivo_adj: "Ver archivo adjunto",
    notareas: "No se han asignado tareas aún.",
    sube: "Sube tu tarea de Deportes",
    archivo2: "Archivo (PDF, DOCX, JPG...):",
    subir: "Subir tarea",
    subidas: "Tareas subidas",
    ver_archivo: "Ver archivo",
    fecha_subida: "Fecha de subida",
    eliminar: "Eliminar",
    eliminar_texto: "Eliminar",
    no_subidas: "No has subido tareas aún.",
    no_permiso_subir: "No tienes permisos para subir tareas.",
    lista: "Lista de Alumnos",
    material_materia: "Material de la materia",
    no_clase: "⚠️ Clase no especificada.",
    material_titulo: "Título del material",
    material_desc: "Descripción del material",
    material_descargar: "Descargar archivo",
    descargar_archivo: "Descargar archivo",
    material_fecha: "Subido el",
    no_materiales: "No hay materiales disponibles para esta clase.",
    descripcionB: "Descripción de la tarea",
    archivos: "Subir archivos:",
    enlace: "Añadir enlace:",
    agregarE: "Agregar enlace",
        maestro_panel_title: "Panel del Maestro | Edusoft",
    maestro_panel_nombre: "Docente",
    maestro_panel_inicio: "Inicio",
    maestro_panel_cursos: "Cursos",
    maestro_panel_alumnos: "Alumnos",
    maestro_panel_tareas: "Tareas",
    maestro_panel_materiales: "Materiales",
    maestro_panel_avisos: "Avisos",
    maestro_panel_mensajes: "Mensajes",
    maestro_panel_perfil: "Perfil",
    maestro_panel_salir: "Salir",
    maestro_panel_cursos_num: "3",
    maestro_panel_cursos_asignados: "Cursos asignados",
    maestro_panel_ver_cursos: "Ver cursos",
    maestro_panel_alumnos_num: "9",
    maestro_panel_total_alumnos: "Alumnos",
    maestro_panel_ver_alumnos: "Ver alumnos",
    maestro_panel_tareas_num: "3",
    maestro_panel_tareas_pendientes: "Tareas pendientes",
    maestro_panel_ver_tareas: "Ver tareas",
    maestro_panel_bienvenido: "Bienvenido,",
    maestro_panel_nombre2: "Docente",
    maestro_panel_intro: "Desde este panel puedes gestionar tus cursos, tareas, materiales, avisos y comunicarte con tus alumnos.",
    maestro_panel_notificaciones_titulo: "Notificaciones recientes",
    maestro_panel_notif_1: "Juan Pérez entregó la tarea \"Ensayo de Historia\".",
    maestro_panel_notif_2: "Nuevo mensaje de Ana López.",
    maestro_panel_notif_3: "Se publicó un aviso en el curso \"Matemáticas 2\".",
    maestro_panel_mis_cursos: "Mis cursos",
    maestro_panel_crear_curso: "Crear curso",
    maestro_panel_link_curso: "Ir al curso",
    maestro_panel_codigo_clase: "Código de clase:",
    maestro_panel_no_clases: "No has creado ninguna clase aún.",
    maestro_panel_titulo_alumnos: "Alumnos",
    maestro_panel_buscar_alumno: "Buscar alumno...",
    maestro_panel_alumno1: "Juan Pérez",
    maestro_panel_alumno2: "Ana López",
    maestro_panel_alumno3: "Carlos Ruiz",
    maestro_panel_alumno4: "María Torres",
    maestro_panel_alumno5: "Lucía Díaz",
    maestro_panel_alumno6: "Sofía Romero",
    maestro_panel_alumno7: "Miguel Ángel",
    maestro_panel_alumno8: "Luis Gómez",
    maestro_panel_alumno9: "Pedro Sánchez",
    maestro_panel_titulo_tareas: "Tareas",
    maestro_panel_tarea_titulo: "Título de la tarea",
    maestro_panel_tarea_materia: "Materia",
    maestro_panel_tarea_fecha_entrega: "Fecha entrega:",
    maestro_panel_eliminar_tarea: "Eliminar",
    maestro_panel_no_tareas: "No hay tareas registradas aún.",
    maestro_panel_crear_tarea: "Crear tarea",
    maestro_panel_titulo_materiales: "Materiales",
    maestro_panel_nombre_clase: "Nombre de la clase",
    maestro_panel_materia_clase: "Materia de la clase",
    maestro_panel_no_clase_seleccionada: "📂 No hay clase seleccionada.",
    maestro_panel_material_titulo: "Título del material",
    maestro_panel_material_archivo: "Archivo",
    maestro_panel_material_fecha: "Subido el",
    maestro_panel_eliminar_material: "Eliminar",
    maestro_panel_no_materiales: "📂 No hay archivos registrados para esta clase.",
    maestro_panel_subir_material: "Subir material",
    maestro_panel_titulo_avisos: "Avisos",
    maestro_panel_aviso1: "Nuevo aviso en Matemáticas 2°A: \"Examen el viernes\".",
    maestro_panel_aviso2: "Reunión con padres el 25/06/2025.",
    maestro_panel_titulo_mensajes: "Mensajes recientes",
    maestro_panel_mensaje1: "Mensaje de Ana López: \"¿Cuándo es la entrega?\"",
    maestro_panel_mensaje2: "Mensaje de Juan Pérez: \"No entiendo la tarea\".",
    maestro_panel_titulo_perfil: "Perfil",
    maestro_panel_input_nombre: "Nombre",
    maestro_panel_input_img: "URL de foto",
    maestro_panel_guardar_cambios: "Guardar cambios",
    crear_clase_titulo: "Crear Clase",
    crear_clase_bienvenida: "Bienvenido, Profesor",
    crear_clase_subtitulo: "Crear una nueva clase",
    crear_clase_mensaje: "Faltan campos obligatorios.",
    crear_clase_label_nombre: "Nombre de la clase:",
    crear_clase_input_nombre: "",
    crear_clase_label_materia: "",
    crear_clase_materia: "Materia:",
    crear_clase_select_materia: "",
    crear_clase_option_default: "-- Selecciona una materia --",
    crear_clase_option_matematica: "Matemática",
    crear_clase_option_biologia: "Biología",
    crear_clase_option_sociales: "Sociales",
    crear_clase_option_lenguaje: "Lenguaje",
    crear_clase_label_descripcion: "Descripción:",
    crear_clase_textarea_desc: "Describe brevemente la clase...",
    crear_clase_btn_codigo: "🔐 Generar código",
    crear_clase_label_codigo_generado: "Código generado:",
    crear_clase_codigo_generado: "---",
    crear_clase_btn_submit: "CREAR CLASE",
    crear_clase_modal_exito: "✅ Clase creada con éxito",
    crear_clase_modal_exito_desc: "Tu clase ha sido registrada correctamente.",
    crear_clase_modal_aceptar: "Aceptar"




    

    

  



  


  

             
             


    // Agrega más claves y textos en español
  },
  en: {
    welcome: "EDUSOFT",
    subtitle: "Welcome to our global learning platform. Access study material from anywhere and achieve your academic goals. Start today!",
    join_now: "Join Now",
    iniciativas:"Initiatives" ,
    parrafo_i: "",
    leer_mas:"read more" ,
    mision:"Mission" ,
    parrafo_m: "Help all students who lack the technology or services to integrate into a better, more advanced education.",
    leer_mas: "read more",
    noticias:"News",
    parrafo_n:"",
    leer_mas:"read more",
    participa:"Participate",
    parrafo_p: "",
    leer_mas:"read more",
    abajo: "2025 in numbers",
    mil:"thousand",
    dolares:"Dollars collected",
    alumnos:"Students graduates",
    centros:"Centers technological",
    inicio:"start",
    cursos:"courses",
    nosotros:"us",
    contacto:"contact",
    biblioteca:"library",
    tutoriales:"tutorials",
    preguntas_frecuentes:"frequently asked questions",
    soporte:"medium",
    legal:"legal",
    terminos:"Terms of Use",
    politica:"Privacy Policy",
    cookies:"Cookies",
    copy:"2024 EDUSOFT - Educational Platform. Developed by technical high school students.", 
    innovacion:"Digital Educational Innovation",
    estudiantes:"students",
    prefesores:"teachers",
    materias:"subjects",
    bienvenida:"Welcome back to our educational platform.",
    bienvenida2: "Welcome to our educational platform",
    desarrollo:"Developed by students, for students and teachers",
    educador:"Educator",
    soyprofe:"I am a teacher",
    p_profe:"Advanced tools to efficiently create, manage, and evaluate educational content",
    gestion:"Class Management",
    subir:"Upload Content",
    analasis:"Progress Analysis",
    evaluaciones:"Evaluations",
    acceder_como:"Access as a teacher",
    estudiante:"Student",
    soyestudiante:"I am student",
    p_estudiante:"Access interactive courses, complete activities, and track your personalized academic progress.",
    cursos:"Interactive Courses",
    actividades:"Actividades",
    logros:"Achievements",
    progreso:"My Progress",
    acceder_estudiante:"Access as a Student",
    porque:"Why choose our platform?",
    desorrollada:"Developed by Students",
    creado:"Created by technical high school students who understand the real needs of modern learning",
    tecnologias:"Modern Technology",
    tecnologia:"We use the latest web technologies to offer a fast, secure and reliable experience",
    comunidad:"Active Community",
    aprendizaje:"Únete a una comunidad de aprendizaje donde estudiantes y profesores colaboran activamente",
    edusoft:"Developed with by Technical Baccalaureate students",
    nosotros:"our",
    ayuda:"help",
    contacto:"contact",
    bienvenidaD:"Welcome teacher",
    cuentaD:"Create an Account",
    nombre_usuario:"User name",
    correo:"Email",
    contraseña:"password",
    telefono:"phone",
    Dui:"ID",
    campos:"All fields are required",
    correcion:"You have registered successfully",
    bienvenidaE:"Welcome student",
    registrar:"Register",
    denuevo:"Welcome back student",
    inicioS:"Login",
    correcto:"Register correctly",
    iniciar:"start",
    denuevoD:"Welcome back teacher",
    confirmar:"confirm password",
    inicioN:"start",
    ProgramasN:"Academic Programs",
    ActividadesN:"Extracurricular activities",
    primaria:"Primary",
    secundaria:"Secondary",
    bachillerato:"High school",
    cursosN:"Courses",
    biologiaN:"Biology",
    lenguajeN:"Language",
    cienciasN:"Science",
    matematicasN:"Matemática",
    quimicaN:"Chemistry",
    Ciencias_socialesN:"Social Sciences",
    calendario:"Calendar",
    nosotros:"Us",
    comunidadN:"Comunidad",
    profesoresN:"Teachers",
    alumnos:"Students",
    padresN:"Parents",
    exalumnos:"alumni",
    noticiasN:"News",
    contactoN:"Contact ",
    cerrarN:"fail session",
    bienvenido:"Welcome",
    cursos:"Our courses",
    biologia:"Biology",
    lenguaje:"Lenguage",
    ciencias:"Science",
    matematicas:"mathematicas",
    mas_informacion:"more information",
    noso:"US",
    Nestudiantes:"Technical high school students creating the future of digital education",
    somosN:"Who We Are",
    somosP2:"We combine our technical expertise with a fresh vision of education to create innovative solutions that facilitate access to knowledge. We believe that technology should be a bridge, not a barrier, to effective learning.",
    somosP:"We are a team of passionate students from the Technical Baccalaureate in Software Development at Don Bosco School. Our educational platform began as a school project and has evolved into a comprehensive tool for digital learning.",
    somosp3:"Democratize access to quality education through innovative technological tools, developed by and for students, that facilitate collaborative and personalized learning.",
    somosp4:"To be recognized as pioneers in the development of student-created digital educational solutions, inspiring new generations to use technology as a tool for social transformation.",
    somosp5:"We are constantly looking for new ways to enhance the educational experience through technology.",
    somosp6:"We believe in the power of teamwork and knowledge sharing to achieve common goals.",
    somosp7:"We strive to make knowledge accessible to everyone, regardless of their circumstances.",
    somosp8:"We are committed to providing the highest quality in every aspect of our educational platform.",
    somosp9:"We are students of the Technical Baccalaureate in Software Development, united by a passion for creating technological solutions for education. Each of us brings unique skills that, together, allow us to develop a complete and functional educational platform.",
    somosp10:"We started as a school project for the school science fair, with the idea of creating a simple educational resource platform.",
    somosp11:"We developed the first functional version of the platform and began implementing it in some classes at our school.",
    somosp12:"We expanded the platform to include more subjects and features, receiving regional recognition for our initiative.",
    somosp13:"Today, our platform is used by students from different institutions, and we continue working to improve it every day.",
    misionN:"Our Mission",
    visionN:"Our Vision",
    valoresN:"Our Values",
    innovacionN:"Innovation",
    colaboracion:"Collaboration",
    accesibilidad:"Accessibility",
    excelencia:"Excellence",
    nuestroN:"Our Team",
    front:"Frontend Development",
    especialista:"Specialist in creating intuitive and attractive interfaces for our platform.",
    back:"Backend Development",
    experto:"Expert in the logic and inner workings of our educational platform.",
    trayectoria:"Our Trajectory",
    elN:"The Start",
    pasos:"First Steps",
    crecimiento:"growth",
    actulidad:"Present",
    profesor:"teacher",
    subidas:"uploaded tasks",
    tablon:"Plank",
    tareas:"Homeworks",
    alumnos:"Students",
    avisos:"notices",
    segundo:"Second year B",
    biologiaM:"Biology",
    titulo:"title",
    descripcion:"description",
    fechal:"Deadline",
    archivo:"See attached file",
    notareas:"No tasks have been assigned yet.",
    tarea:"Cell Biology Homework",
    resolver:"Solve the cell biology problems from chapter 3.",
    fecha:"Deadline: April 10",
    sube:"Upload your Biology homework",
    archivo2:"File (PDF, DOCX, JPG...):",
    subir:"UpUploaded tasks",
    proyecto:"Create a Molecular Biology Project",
    crearM:"Create a project on molecular biology.",
    limete:"Deadline: April 12",
    añadir:"Add task",
    examen:"Evolutionary Biology Exam",
    estudiar:"Study for the evolutionary biology exam next Friday.",
    tarea2:"Environmental Biology Homework",
    escribir:"Write an essay on the importance of environmental biology in environmental conservation.",
    lista:"List of Students",
    avisos:"Notices",
    titulo2:"Task Title",
    descripcionB:"Task description",
    archivos:"Upload files",
    enlace:"Add link:",
    agregarE:"Add link",
    ciencia:"science",
    tareaC:"Physics Homework",
    cp1:"Astronomy Project",
    astronomia:"Astronomy Project",
    cp2:"Create a project about the solar system.",
    geologia:"Geology Exam",
    cp3:"Study for the geology exam next Friday.",
    ambiental:"Environmental Science Homework",
    cp4:"Write an essay on the importance of environmental conservation.",
    lenguajeM:"lenguage",
    analasisM:"Text Analysis Task",
    lp:"Analyze the text The House of the Spirits by Isabel Allende",
    proyectol:"Literature Project",
    lp1:"Create a project about the life and work of a literary author.",
    examenl:"Grammar Test",
    lp2:"Study for the grammar test next Friday.",
    composicionl:"Composition Task",
    lp3:"Write an essay on a current topic.",
    h4:"platform",
    recursosP:"resources",
    acceder_estudiante1:"Login as a student",
    acceder_como1:"Login as a teacher",
    inicioV:"Main",
    nosotrosV:"US",
    contactoV:"contact",
    iniciarS:"Login",
    unete:"join",
    nombreCo:"Full name",
    correoCo:"Email",
    asuntoCo:"Affair",
    escribe:"Write your message...",
    enviarCo:"Send message",
    titulo_arte: "EduSoft - Art",
    logo_edusoft: "EduSoft",
    tablon: "Board",
    tareas: "Tasks",
    alumnos: "Students",
    arte_titulo_principal: "Art",
    arte_descripcion: "Explore the world of art and develop your creativity through different activities and projects.",
    arte_titulo_tareas: "Art Tasks",
    arte_tarea_1: "Make a free drawing and upload it before Friday.",
    arte_tarea_2: "Research a famous painter and share your work.",
    arte_titulo_alumnos: "Student List",
    arte_alumno_1: "Juan Perez",
    arte_alumno_2: "Maria Lopez",
    arte_alumno_3: "Carlos Gomez",
titulo_deportes: "EduSoft - Sports",
    logo_edusoft: "EduSoft",
    tablon: "Board",
    tablon_texto: "Board",
    tareas: "Tasks",
    tareas_texto: "Tasks",
    material_texto: "Material",
    alumnos: "Students",
    alumnos_texto: "Students",
    avisos: "Notices",
    avisos_texto: "Notices",
    segundo: "Second year B",
    segundo_texto: "Second year B",
    deportesN: "Sports",
    settings: "Settings",
    profile: "Profile",
    profesor: "Teacher",
    titulo: "Title",
    descripcion: "Description",
    fechal: "Deadline",
    puntos: "Points",
    archivo: "Attachment",
    archivo_adj: "View attachment",
    notareas: "No tasks assigned yet.",
    sube: "Upload your Sports task",
    archivo2: "File (PDF, DOCX, JPG...):",
    subir: "Upload task",
    subidas: "Uploaded tasks",
    ver_archivo: "View file",
    fecha_subida: "Upload date",
    eliminar: "Delete",
    eliminar_texto: "Delete",
    no_subidas: "You haven't uploaded any tasks yet.",
    no_permiso_subir: "You don't have permission to upload tasks.",
    lista: "Student List",
    material_materia: "Subject material",
    no_clase: "⚠️ Class not specified.",
    material_titulo: "Material title",
    material_desc: "Material description",
    material_descargar: "Download file",
    descargar_archivo: "Download file",
    material_fecha: "Uploaded on",
    no_materiales: "No materials available for this class.",
    descripcionB: "Task description",
    archivos: "Upload files:",
    enlace: "Add link:",
    agregarE: "Add link",
        maestro_panel_title: "Teacher Panel | Edusoft",
    maestro_panel_nombre: "Teacher",
    maestro_panel_inicio: "Home",
    maestro_panel_cursos: "Courses",
    maestro_panel_alumnos: "Students",
    maestro_panel_tareas: "Tasks",
    maestro_panel_materiales: "Materials",
    maestro_panel_avisos: "Notices",
    maestro_panel_mensajes: "Messages",
    maestro_panel_perfil: "Profile",
    maestro_panel_salir: "Logout",
    maestro_panel_cursos_num: "3",
    maestro_panel_cursos_asignados: "Assigned courses",
    maestro_panel_ver_cursos: "View courses",
    maestro_panel_alumnos_num: "9",
    maestro_panel_total_alumnos: "Students",
    maestro_panel_ver_alumnos: "View students",
    maestro_panel_tareas_num: "3",
    maestro_panel_tareas_pendientes: "Pending tasks",
    maestro_panel_ver_tareas: "View tasks",
    maestro_panel_bienvenido: "Welcome,",
    maestro_panel_nombre2: "Teacher",
    maestro_panel_intro: "From this panel you can manage your courses, tasks, materials, notices and communicate with your students.",
    maestro_panel_notificaciones_titulo: "Recent notifications",
    maestro_panel_notif_1: "Juan Perez submitted the task \"History Essay\".",
    maestro_panel_notif_2: "New message from Ana Lopez.",
    maestro_panel_notif_3: "A notice was published in the course \"Math 2\".",
    maestro_panel_mis_cursos: "My courses",
    maestro_panel_crear_curso: "Create course",
    maestro_panel_link_curso: "Go to course",
    maestro_panel_codigo_clase: "Class code:",
    maestro_panel_no_clases: "You haven't created any classes yet.",
    maestro_panel_titulo_alumnos: "Students",
    maestro_panel_buscar_alumno: "Search student...",
    maestro_panel_alumno1: "Juan Perez",
    maestro_panel_alumno2: "Ana Lopez",
    maestro_panel_alumno3: "Carlos Ruiz",
    maestro_panel_alumno4: "Maria Torres",
    maestro_panel_alumno5: "Lucia Diaz",
    maestro_panel_alumno6: "Sofia Romero",
    maestro_panel_alumno7: "Miguel Angel",
    maestro_panel_alumno8: "Luis Gomez",
    maestro_panel_alumno9: "Pedro Sanchez",
    maestro_panel_titulo_tareas: "Tasks",
    maestro_panel_tarea_titulo: "Task title",
    maestro_panel_tarea_materia: "Subject",
    maestro_panel_tarea_fecha_entrega: "Due date:",
    maestro_panel_eliminar_tarea: "Delete",
    maestro_panel_no_tareas: "No tasks registered yet.",
    maestro_panel_crear_tarea: "Create task",
    maestro_panel_titulo_materiales: "Materials",
    maestro_panel_nombre_clase: "Class name",
    maestro_panel_materia_clase: "Class subject",
    maestro_panel_no_clase_seleccionada: "📂 No class selected.",
    maestro_panel_material_titulo: "Material title",
    maestro_panel_material_archivo: "File",
    maestro_panel_material_fecha: "Uploaded on",
    maestro_panel_eliminar_material: "Delete",
    maestro_panel_no_materiales: "📂 No files registered for this class.",
    maestro_panel_subir_material: "Upload material",
    maestro_panel_titulo_avisos: "Notices",
    maestro_panel_aviso1: "New notice in Math 2A: \"Exam on Friday\".",
    maestro_panel_aviso2: "Meeting with parents on 25/06/2025.",
    maestro_panel_titulo_mensajes: "Recent messages",
    maestro_panel_mensaje1: "Message from Ana Lopez: \"When is the delivery?\"",
    maestro_panel_mensaje2: "Message from Juan Perez: \"I don't understand the task\".",
    maestro_panel_titulo_perfil: "Profile",
    maestro_panel_input_nombre: "Name",
    maestro_panel_input_img: "Photo URL",
    maestro_panel_guardar_cambios: "Save changes",
    crear_clase_titulo: "Create Class",
    crear_clase_bienvenida: "Welcome, Teacher",
    crear_clase_subtitulo: "Create a new class",
    crear_clase_mensaje: "Required fields are missing.",
    crear_clase_label_nombre: "Class name:",
    crear_clase_input_nombre: "",
    crear_clase_label_materia: "",
    crear_clase_materia: "Subject:",
    crear_clase_select_materia: "",
    crear_clase_option_default: "-- Select a subject --",
    crear_clase_option_matematica: "Math",
    crear_clase_option_biologia: "Biology",
    crear_clase_option_sociales: "Social Studies",
    crear_clase_option_lenguaje: "Language",
    crear_clase_label_descripcion: "Description:",
    crear_clase_textarea_desc: "Briefly describe the class...",
    crear_clase_btn_codigo: "🔐 Generate code",
    crear_clase_label_codigo_generado: "Generated code:",
    crear_clase_codigo_generado: "---",
    crear_clase_btn_submit: "CREATE CLASS",
    crear_clase_modal_exito: "✅ Class created successfully",
    crear_clase_modal_exito_desc: "Your class has been registered successfully.",
    crear_clase_modal_aceptar: "Accept"  

    

    

  
  
  
  
  }
};